version: '3.4'

services:
  
  php:
    build:
      context: ./api
      target: api_platform_php
    image: api
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      - ./api/var:/srv/api/var:rw
  
  api:
    build:
      context: ./api
      target: api_platform_nginx
    image: nginx
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=docler
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  client:
    build:
      context: ./client
      target: api_platform_client_development
    image: client
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    environment:
      - API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT=http://api
      - API_PLATFORM_CLIENT_GENERATOR_OUTPUT=src
    volumes:
      - ./client:/usr/src/client:rw
    ports:
      - target: 3000
        published: 80
        protocol: tcp

volumes:
  data: {}
