version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db-mysql

  db-mysql:
    image: "mysql:5.7"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docler
    volumes:
      - $VOLUME_DIR/data/volume/mysql:/var/lib/mysql
      - $VOLUME_DIR/data/volume/logs/mysql:/var/log/mysql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"
